# on: [push]
# jobs:
#   hello_world_job:
#     runs-on: ubuntu-latest
#     name: A job to say hello
#     steps:
#       # - name: Checkout
#       #   uses: actions/checkout@v3
#       # - name: Hello world action step
#       #   uses: ./
#       #   id: hello
#       #   with:
#       #     who-to-greet: 'Mona the Octocat'
#       # - name: Get the output time
#       #   run: echo "The time was ${{ steps.hello.outputs.time }}"
#       - uses: actions/checkout@v3
#       - id: foo
#         uses: jordan-van-dyk-form3/github-action-playground@v2
#         with:
#           who-to-greet: 'Mona the Octocat'
#       - run: echo random-number ${{ steps.foo.outputs.random-number }}
#         shell: bash


on: 
  workflow_dispatch:
    inputs:
      a_name:
        description: "Someone's name"
        required: true
        default: " a small robot"
      something:
        description: "something neat"
        required: true
        default: "top"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: jordan-van-dyk-form3/composite@main
        with:
          who: ${{ github.event.inputs.a_name }}
          something-neat: ${{ github.event.inputs.something}}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: echo goodbye time ${{ steps.foo.outputs.time }}
      - id: reuse
        uses: jordan-van-dyk-form3/github-action-playground/.github/workflows/main.yml@main
        with:
          secrets:
            superSecret: ${{ secrets.superSecret }}
